### ISSUE TITLE
Request for a new release 0.6.1 or 0.6.1-prerelease

### ISSUE THREAD

**Issue by pethers** [highsource/hyperjaxb3#24]
I understand you are busy, but would it be possible with a release on the current state of the code.

Use hyperjaxb3 at work together with cxf, 0.6.1-SNAPSHOT contains support for xjc 2.2.11.

Can't upgrade to cxf 3.x or 3.1.x without 0.6.1-SNAPSHOT since that version of cxf-codegen-plugin uses xjc 2.2.11 and causes conflicts with 0.6.0.  

Problem to release with maven with snapshots dependencies, could always change versions myself and deploy to our internal company maven repository. But would like to avoid having "fake" versions.

**Comment by highsource** [comment]
Does 0.6.1 "as is" work for you?

**Comment by pethers** [comment]
Would be perfect, don't have any problems with it.

**Comment by pethers** [comment]
Thank you for the release, but can't find the released version anywhere.

Have you published 0.6.1 to any maven repository ? 

Can only find https://oss.sonatype.org/content/repositories/snapshots/org/jvnet/hyperjaxb3/ 0.6.1-SNAPSHOT updated Mon Nov 23.

**Comment by highsource** [comment]
It's not released yet, issue was mistakenly closed. I'm still fighting a bit with tests and release scripts.

**Comment by highsource** [comment]
Ok, NOW it is released.
