### ISSUE TITLE
Change of table name generation in version 0.6.0

### ISSUE THREAD

**Issue by bhausen** [highsource/hyperjaxb3#26]
I switched from version 0.5.6 to 0.6.0. 

The maven plugin org.jvnet.hyperjaxb3:maven-hyperjaxb3-plugin:0.5.6 generates table names for a complexType named OperationStateType the table name OPERATIONSTATETYPE. 

Plugin org.jvnet.hyperjaxb3:maven-hyperjaxb3-plugin:0.6.0 generates OPERATION_STATE_TYPE.

Could you please give an advice, how to get the old table names with version 0.6.0?
```
<complexType name="OperationStateType">
	<sequence>
		<element name="operationUUID" type="string" />
		<element name="state" type="string" />
	</sequence>
</complexType>
```

**Comment by pethers** [comment]
Had the same problem, adding 

<dependency>
	<groupId>org.jvnet.hyperjaxb3</groupId>
	<artifactId>hyperjaxb3-ejb-extensions-custom-naming-pre_0_6_0</artifactId>
	<version>0.6.1</version>
</dependency>

as a dependency to the maven-hyperjaxb3-plugin uses the old naming convention. Not sure if using it together with 0.6.0 causes any problem, but worth testing.

**Comment by bhausen** [comment]
Bad luck. This did not work. 
Some other suggestions?

**Comment by bhausen** [comment]
Now after moving to version 0.6.1 my maven plugin definition looks like the following. But still I get the table name OPERATION_STATE_TYPE instead of OPERATIONSTATETYPE in the generated java source. Did I something wrong here?
```
<plugin>
	<groupId>org.jvnet.hyperjaxb3</groupId>
	<artifactId>maven-hyperjaxb3-plugin</artifactId>
	<version>0.6.1</version>
	<executions>
		<execution>
			<id>generate-hyperjaxb3-sources</id>
			<phase>generate-resources</phase>
			<goals>
				<goal>generate</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<forceRegenerate>true</forceRegenerate>
		<schemaDirectory>${model.dir}</schemaDirectory>
		<verbose>false</verbose>
		<variant>jpa2</variant>
		<persistenceXml>${project.basedir}/src/main/persistence/persistence-template.xml</persistenceXml>
		<episode>true</episode>
		<generateDirectory>${java.gen.dir}</generateDirectory>
		<extension>true</extension>
		<persistenceUnitName>${persistence.unit.name}</persistenceUnitName>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>org.jvnet.hyperjaxb3</groupId>
			<artifactId>hyperjaxb3-ejb-extensions-custom-naming-pre_0_6_0</artifactId>
			<version>0.6.1</version>
		</dependency>
	</dependencies>
</plugin>
```

**Comment by bhausen** [comment]
Hi all,

found the old 0.5.6 DefaultNaming sources. I will pass a link to the sources working for jpa1 and jpa2 too.

**Comment by bhausen** [comment]
I need to keep already existing table and column names stable - even if I swicht to the newest version of hyperjaxb3. In here, it is not enough to replace the `_` ` ` (an empty string). In 0.5.6 joined columns or table and column names longer than 30 characters contained `_` too. For that reason I copied the behaviour of 0.5.6.

Steps taken:
* Incorporated the 0.5.6 getName(String) method into Class com.qpark.eip.hyperjaxb3.naming.Pre600DefaultNaming
* Added applicationContext.xml for pathes 
 * org/jvnet/hyperjaxb3/ejb/plugin/custom,
 * org/jvnet/hyperjaxb3/ejb/jpa1/plugin/custom and
 * org/jvnet/hyperjaxb3/ejb/jpa2/plugin/custom

May at one time the `org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin` line 144 and 147 could use EjbPlugin.class instead of getClass(). In that case the distribution of the applicationContext.xml files would not be needed.

I would appreciate, if the `org.jvnet.hyperjaxb3.ejb.plugin.EjbPlugin` and the `hyperjaxb3-ejb-extensions-custom-naming-pre_0_6_0` jar would be enhanced with my ideas.

See: [QPark/EIP eip-hyperjaxb3-naming]
(https://github.com/QPark/EIP/tree/master/qp-enterprise-integration-platform/eip-hyperjaxb3-naming)

**Comment by highsource** [comment]
Hi @bhausen,

sorry I could not react earlier.

The best you could do is to send me a pull request with your custom strategies. The best would be creating an extension here:

https://github.com/highsource/hyperjaxb3/tree/master/ejb/extensions/naming/custom-naming-pre_0_5_6

Additionally please consider adding a test project here:

https://github.com/highsource/hyperjaxb3/tree/master/ejb/tests/custom-naming-pre_0_5_6

So that your extension will be tested during the build.

Generally, custom naming strategy is exactly the right solution here. Sometimes there are backwards incompatible changes, we can't avoid it. But configurable strategies allow you to override it to get old conventions back. This is exactly why that's strategies and that they're configurable.

Best wishes,
Alexey
