### ISSUE TITLE
[question] Interface for custom JPA strategy generation

### ISSUE THREAD

**Issue by archenroot** [highsource/hyperjaxb3#36]
As we all know :-) XSD and JPA are not always friends and in some case one might need kind of override for its specific use case.

Is there any kind of interface in hyperjaxb where I could override the default JPA generation strategy or enhance it,? **Imagine I would like to generate createdOn, UpdatedOn, etc. columns to every entity for example.**

Background: I model XSD first for even bus. I support both XML and JSON messages (detected on the fly). Preferred is JSON, so I generate JSON schemas from XSD as well. Now I would like to first persists objects for later generation REST API, with Spring Data JPA and Spring Data REST...

Thanks for any hints.

**Comment by highsource** [comment]
You can override many defaults via configuration. Here's a example of the configuration:

https://github.com/highsource/hyperjaxb3/blob/master/ejb/tests/cu-one/src/main/resources/bindings.xjb

Schema for customizations:

https://github.com/highsource/hyperjaxb3/tree/master/ejb/schemas/customizations/src/main/resources

You can also override/extend how HJ3 generates things on the code level, see this example:

https://github.com/highsource/hyperjaxb3/tree/master/ejb/tests/custom-naming

**Comment by archenroot** [comment]
@highsource brilliant. The more I look into the hyperjaxb3 the more I see how it is designed in robust way against some other projects I found (all dead anyway)...
