### ISSUE TITLE
[docs] Is there any duplicate of content from non-existing site confluence.highsource.org?

### ISSUE THREAD

**Issue by archenroot** [highsource/hyperjaxb3#37]
I found via google lot of links pointing to confluence.highsource.org, but the site doesn't exist anymore, is the content available somewhere else?

**Comment by bhausen** [comment]
See issue 31 https://github.com/highsource/hyperjaxb3/issues/31. You may ask for a restart of the old server :-)

**Comment by jimternet** [comment]
if we can bring it back up - should we migrate to github pages?

**Comment by highsource** [comment]
I'll try to start the server in the evening (in a few hours).

Migration to GitHub Pages would be great but it is quite effort-intensive. I have started https://github.com/highsource/confluence-to-markdown-converter a while ago but that was very far from fully automated. (I'd actually prefer migration to GitHub Wiki.)

If someone is willing to give it a try, I'll definitely accept PRs.

**Comment by highsource** [comment]
http://confluence.highsource.org/dashboard.action back online (at the moment).

**Comment by jimternet** [comment]
can you export the html of the confluence pages? I will take care of the conversion!

Go to the space and choose Space tools > Content Tools on the sidebar.
Choose Export.
Select HTML then choose Next.

**Comment by highsource** [comment]
@jimternet Here you go:
[Confluence-space-export-064704-12.html.zip](https://github.com/highsource/hyperjaxb3/files/1265834/Confluence-space-export-064704-12.html.zip)

Thanks, I did not know there existed this option.

**Comment by jimternet** [comment]
https://github.com/jimternet/hyperjaxb3/wiki

**Comment by jimternet** [comment]
you can't do a PR for wiki material I guess. 😞

**Comment by highsource** [comment]
OMG how did you convert that?

**Comment by highsource** [comment]
Copied here:

https://github.com/highsource/hyperjaxb3/wiki

@jimternet Great work, I'm very interested how you did that.

**Comment by jimternet** [comment]
https://www.npmjs.com/package/confluence-to-markdown

I barely did anything :) Just good at googling I guess 🤷‍♂️

**Comment by highsource** [comment]
@jimternet Last time I googled that I ended up with this:
https://github.com/highsource/confluence-to-markdown-converter

Cool you did the conversion, many thanks.
