### ISSUE TITLE
hyperjaxb3-ejb-template-basic-0.5.6-maven cannot be download

### ISSUE THREAD

**Issue by ikonny** [highsource/hyperjaxb3#49]
Hi Alexey
I am new java developer and recently I encountered some issue when trying to persist xml to database, Luckly  I found hyperjaxb3, but the problem is I can not download the template by referring to http://repository.highsource.org/maven2/releases/org/jvnet/hyperjaxb3/hyperjaxb3-ejb-template-basic/0.5.6/hyperjaxb3-ejb-template-basic-0.5.6-maven-src.zip, so could you please give me a valid url for template code?

**Comment by highsource** [comment]
See  [Releases](https://github.com/highsource/hyperjaxb3/releases).
