### ISSUE TITLE
Help please. RoundtripTest is working but I get 'No Persistence provider for EntityManager named generated' error.

### ISSUE THREAD

**Issue by cenkozan** [highsource/hyperjaxb3#51]
Sorry for posting this question as I know you hate it but please help.

I uploaded my project to [here](https://github.com/cenkozan/hyperjaxb3). I would be very pleased if you could take a look to see what is wrong with my setup.

I am just trying to make your purchase order example working.

Thank you.

**Comment by highsource** [comment]
I've forked and built your project with `mvn clean install -X`. It built without any problems from the first time. Here's the log:

[std.txt](https://github.com/highsource/hyperjaxb3/files/1990649/std.txt)

Please post your complete `mvn clean install -X` log.

**Comment by highsource** [comment]
@cenkozan I don't get it. You build shows:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.773 s
[INFO] Finished at: 2018-05-10T08:19:00+01:00
[INFO] ------------------------------------------------------------------------
````

What is the problem?

**Comment by cenkozan** [comment]
I am trying to run the Joe.java class. Please check that file. 
When I run 
`entityManagerFactory = Persistence.createEntityManagerFactory(
                "generated", persistenceProperties);`
It throws 'No Persistence provider for EntityManager named generated'.

**Comment by highsource** [comment]
I have no idea why it doesn't work. Roundtrip test works allright, but your `Joe` class does not, despite it seemingly does the same thing. I don't understand it.

**Comment by cenkozan** [comment]
Yes, Alexey. It is very strange. Thank you for taking a look anyway. I will close this issue in a day.

**Comment by highsource** [comment]
You have to remove `<scope>test</scope>` from `hibernate-entitymanager` in your `pom.xml`.
Hibernate was effectively only available for test classes.

**Comment by cenkozan** [comment]
Oh yes. Thank you so much, Alexey! You are the greatest!

**Comment by highsource** [comment]
This still does not work well in Eclipse. For one you have to use a binding file as follows:

```
<jaxb:bindings version="1.0" xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
	xmlns:hj="http://hyperjaxb3.jvnet.org/ejb/schemas/customizations"
	jaxb:extensionBindingPrefixes="xjc">
	
	<jaxb:bindings schemaLocation="po.xsd" node="/xs:schema">
		<jaxb:globalBindings localScoping="toplevel">
			<jaxb:serializable/>
		</jaxb:globalBindings>
	</jaxb:bindings>

</jaxb:bindings>
```

Otherwise Eclipse does not like that `Items.Item` is generated as a nexted class.

But then it still does not work, classes in `generated` could not be found. I don't know why is it so, maybe Eclispe thinks that `target/generated-sources/xjc` are only test classes. I don't know.

**Comment by cenkozan** [comment]
Hmm. Should I keep this issue open till I fix everything, Alexey?

**Comment by highsource** [comment]
No, I won't do anything here anymore. I know it works since roundtrip tests run successfully and I'll cowardly ignore Eclipse issues.

**Comment by cenkozan** [comment]
Thank you so much for your help, Alexey. Cheers and all the best!!!
