### ISSUE TITLE
API incompatibility with jaxb2-basics-annotate 1.1.0

### ISSUE THREAD

**Issue by vennekilde** [highsource/hyperjaxb3#52]
I needed to update to jaxb2-basics-annotate 1.1.0 in order to get support for removing annotations, however compiling my project afterwards will result in the following error

`Failed to execute goal org.jvnet.hyperjaxb3:hyperjaxb3-maven-plugin:0.6.2:generate (generate-domain1) on project DREM-TPS-Backend: Execution generate-domain1 of goal org.jvnet.hyperjaxb3:hyperjaxb3-maven-plugin:0.6.2:generate failed: An API incompatibility was encountered while executing org.jvnet.hyperjaxb3:hyperjaxb3-maven-plugin:0.6.2:generate: java.lang.IllegalAccessError: tried to access field org.jvnet.jaxb2_commons.plugin.annotate.AnnotatePlugin.ANNOTATE_PACKAGE_QNAME from class org.jvnet.jaxb2_commons.plugin.AnnotationTarget`

The compilation error will not occur, as long as no <annox:removeAnnotation ...> is defined in your bindings configuration. Specifically <annox:removeAnnotation class="javax.persistence.Transient" /> in my case

**Comment by highsource** [comment]
PR welcome. :)

**Comment by laurentschoelens** [comment]
Hi @vennekilde 

Hyperjaxb3 has been merged into [jaxb-tools]lhttps://github.com/highsource/jaxb-tools) repository which also contains jaxb-annotate mentionned here.

You can check the [migration guide](https://github.com/highsource/jaxb-tools/wiki/JAXB-Tools-Migration-Guide#migration-from-previous-version-0x--1x-to-v2) to get the latest version of both artifacts

Regards
